version: '3'
services:
  watchtower:
    image: v2tec/watchtower:armhf-latest
    container_name: watchtower
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always
  rpi-server:
    image: ezhai24/rpi-server
    container_name: rpi-server
    ports:
      - "49861:20000"
    restart: always
  pydio:
    image: jordancrawford/rpi-pydio-docker
    container_name: pydio
    ports:
      - "80:80"
      - "443:443"
    restart: always